### ISSUE TITLE
Is browser automation allowed in zerodha?

### ISSUE THREAD

**Issue by mesmitpatel** [vinaykachare/ZerodhaRequestToken#1]
I am also trying to achieve something similar... So I was doing a bit of research, found few queries ([one of them](https://kite.trade/forum/discussion/comment/9915/#Comment_9915)) about if we could use _browser automation_ for login on Zerodha forums, but turns out most of the users are hesitant to do so because they don't allow full automation. I wanted to know if you've been using this & if you've faced any issues or something.

**Comment by vinaykachare** [comment]
Yes, I'm using it for my algo's without any issue till now. as the script just automate the manual process of generating token.

**Comment by mesmitpatel** [comment]
Okay. Thanks for the quick reply! 🤙🏼😀
